### ISSUE TITLE
osv-scanner: integrate vulncheck

### ISSUE THREAD

**Issue by oliverchang** [google/osv-scanner#10]
https://pkg.go.dev/golang.org/x/vuln/vulncheck does static analysis to check callgraphs etc. Perhaps we can re-use this in our osv-scanner.

**Comment by oliverchang** [comment]
The initial PR landed in https://github.com/google/osv-scanner/pull/198 as an experimental feature. 

What's left now is to test this and stabilise this.

**Comment by another-rex** [comment]
This is now stablized
