### ISSUE TITLE
Errors spamming the stderr output

### ISSUE THREAD

**Issue by another-rex** [google/osv-scanner#1005]
Some errors should only be displayed once, but spams the output because of its location in the code flow.

Currently the only example of this I have is :

https://github.com/google/osv-scanner/blob/main/internal/local/check.go/#L147-L148

Solution proposed:
Have some global hashmap that checks if this error has already been logged and don't repeat the log.

**Comment by G-Rath** [comment]
Can you provide a reproduction for that specific example? as it sounds like a potential bug.

The whole concept though of not spamming errors sounds good

**Comment by another-rex** [comment]
Call `osv-scanner --experimental-offline .` without a local-db already set up, and it'll print one error per package that's scanned, since the error is in `MakeRequest`. So it's working as intended, it's just not great UX.

**Comment by marcwieserdev** [comment]
So it seems to make the job for us, I'll close this PR then, thanks a lot for your insight :)
