### ISSUE TITLE
OSV API Reveals Vulnerability Despite Detection Failure using osv-scanner

### ISSUE THREAD

**Issue by edwinjhlee** [google/osv-scanner#1013]
## abstract

Since osv-scanner cannot support dnf package manager(https://github.com/google/osv-scanner/issues/999), and we are informed that osv-scanner can take output from syft (https://github.com/google/osv-scanner/issues/991) , now we are managing to use syft to generate bom and 
try to use osv-scanner to detect the vuln.

osv-scanner fail to detect the vuln using the sbom. But we can retrieve the vuln information using the ( git 2.39.1-1.el8 ) in the OSV API.

the osv-scanner version we are using is **1.7.3**

## detail

We using syft to generate the sbom.

```bash
syft dir:/var/lib/rpm -o cyclonedx-json > sbom.spdx.json
```

We notice syft detect git with version =  "2.39.1-1.el8"

```json
        {
            "bom-ref": "pkg:rpm/git@2.39.1-1.el8?arch=x86_64&upstream=git-2.39.1-1.el8.src.rpm&package-id=9dba9f141d16f8cb",
            "type": "library",
            "publisher": "CentOS",
            "name": "git",
            "version": "2.39.1-1.el8",
            "licenses": [
                {
                    "license": {
                        "name": "GPLv2"
                    }
                }
            ],
            "cpe": "cpe:2.3:a:centos:git:2.39.1-1.el8:*:*:*:*:*:*:*",
            "purl": "pkg:rpm/git@2.39.1-1.el8?arch=x86_64&upstream=git-2.39.1-1.el8.src.rpm",
            "properties": [
                {
                    "name": "syft:package:foundBy",
                    "value": "rpm-db-cataloger"
                },
                {
                    "name": "syft:package:type",
                    "value": "rpm"
                },
                {
                    "name": "syft:package:metadataType",
                    "value": "rpm-db-entry"
                },
                {
                    "name": "syft:cpe23",
                    "value": "cpe:2.3:a:git:git:2.39.1-1.el8:*:*:*:*:*:*:*"
                },
                {
                    "name": "syft:location:0:path",
                    "value": "/Packages"
                },
                {
                    "name": "syft:metadata:release",
                    "value": "1.el8"
                },
                {
                    "name": "syft:metadata:size",
                    "value": "135705"
                },
                {
                    "name": "syft:metadata:sourceRpm",
                    "value": "git-2.39.1-1.el8.src.rpm"
                }
            ]
        },
```

We can retreive the relative vuln using OSV API  in this combinartion ( git 2.39.1-1.el8 )

```bash
    curl -d \
      '{"package": {"name": "git"}, "version": "2.39.1-1.el8"}' \
      "https://api.osv.dev/v1/query"
```

Now my question is why we cannot detect the vuln using command:

```bash
osv-scanner --sbom=sbom.spdx.json
```

[sbom.spdx.json](https://github.com/user-attachments/files/15508399/240530.sbom.spdx.json)

**Comment by edwinjhlee** [comment]
The grype can detect the vuln using redhat vuln database.

```
grype --distroad rhel:8 sbom:sbom.json
```

I understand that the osv haven't integrate the redhat vuln db. But it seemed the vuln info exsists in other data sources, osv-scanner have enough information to detect the vuln.

**Comment by another-rex** [comment]
OSV always(?) take the ecosystem into account when making queries, and since we don't yet ingest the redhat vuln db, it fails to find any vulnerabilities for redhat. E.g. it essentially does this query:

```
curl -d  
    '{"package": {"purl": "pkg:rpm/git?arch=x86_64&upstream=git-2.39.1-1.el8.src.rpm"}, "version": "2.39.1-1.el8"}' \
    "https://api.osv.dev/v1/query"
```
which would be parsed into something like this in the backend:
```
 curl -d \
      '{"package": {"name": "git", "ecosystem": "redhat"}, "version": "2.39.1-1.el8"}' \
      "https://api.osv.dev/v1/query"
```

The reason we don't make any queries without an ecosystem is mainly because we want to return the relevant advisory from the correct language/OS. Without an ecosystem the name could also refer to a language package.

We also want to avoid false positives, E.g. an OS distro might have patched the git package on that version, but kept the version number, so showing a Bitnami advisory won't be relevant. (Though this is not very common)

**Comment by edwinjhlee** [comment]
**Thank you for your explanations. I now understand why the issue occurs.**

**I have a couple of questions:**

1. Is there a parameter within OSV-SCANNER that allows for increased tolerance of false positives ?
2. Are there any plans to integrate the Red Hat database into OSV source?

---

I am implementing osv client in x-cmd and integrate osv-scanner in the client. 
This is the demo.
https://x-cmd.com/mod/osv

---

The next version of x-cmd will try to use llm to interprete the osv report. 

The LLM might be capable to filter out the **false positive** for user.

**Comment by edwinjhlee** [comment]
Here is the grype --distro ID:

https://pkg.go.dev/github.com/anchore/grype/grype/distro#RockyLinux

<img width="954" alt="image" src="https://github.com/google/osv-scanner/assets/4426319/5b4eb3b2-4f1b-4797-8d20-66e60ddc701e">

**Comment by andrewpollock** [comment]
> 2\. Are there any plans to integrate the Red Hat database into OSV source?

@mprpic FYI 😺

**Comment by andrewpollock** [comment]
> We can retreive the relative vuln using OSV API in this combinartion ( git 2.39.1-1.el8 )
> 
> ```shell
>     curl -d \
>       '{"package": {"name": "git"}, "version": "2.39.1-1.el8"}' \
>       "https://api.osv.dev/v1/query"
> ```

To add further detail here: without `ecosystem` included in the query, the API is returning https://osv.dev/vulnerability/BIT-git-2024-32002, which is for Bitnami, which may be relevant in this particular case, isn't necessarily always going to be, per @another-rex in https://github.com/google/osv-scanner/issues/1013#issuecomment-2141271791

**Comment by andrewpollock** [comment]
Also, x-cmd in general looks pretty slick, and the integration with OSV is very cool! Please feel free to send a PR to add a mention to [https://github.com/google/osv.dev/blob/master/README.md](https://github.com/google/osv.dev?tab=readme-ov-file#third-party-tools-and-integrations)

**Comment by edwinjhlee** [comment]
> Also, x-cmd in general looks pretty slick, and the integration with OSV is very cool! Please feel free to send a PR to add a mention to [https://github.com/google/osv.dev/blob/master/README.md](https://github.com/google/osv.dev?tab=readme-ov-file#third-party-tools-and-integrations)

Thank you for the invitation ~
