### ISSUE TITLE
Github Actions: The workflow is requesting 'actions: read'

### ISSUE THREAD

**Issue by faern** [google/osv-scanner#1090]
I tried integrating `osv-scanner` into our Github Actions workflows according to the docs at https://google.github.io/osv-scanner/github-action/#scan-on-pull-request

But when trying to run it I get the following error:
```
The workflow is not valid. .github/workflows/osv-scanner-pr.yml (Line: 15, Col: 3): Error calling workflow 'google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@f0e45d2960258cf40285d596a10f817af70af1f7'. The workflow is requesting 'actions: read', but is only allowed 'actions: none'.
```

This can be fixed by adding `actions: read` into the `permissions` section. However, I'm not submitting a PR with the change since I don't know if it's the best fix, or if this is a regression that should be fixed in other ways.

**Comment by cuixq** [comment]
@another-rex

**Comment by faern** [comment]
I should mention that I dont use the version of the action from the guide, but the latest, 1.7.4

**Comment by another-rex** [comment]
Thanks for making this issue! We did update to require action: read, but failed to update the docs, made a PR which will address this.
