### ISSUE TITLE
Windows binary is flagged by Virustotal (Google AV)

### ISSUE THREAD

**Issue by ckrueger1979** [google/osv-scanner#111]
Hi,

right now [osv-scanner_1.0.2_windows_amd64.exe](https://github.com/google/osv-scanner/releases/download/v1.0.2/osv-scanner_1.0.2_windows_amd64.exe) is flagged by the Google AV engine in Virustotal:
https://www.virustotal.com/gui/file/ac9c77d9a5e91e8050b2aa5af9e13c5547775ae969d51ae957e08a8dc3804764

Codesigning of the binaries wouldn't hurt.

greetings
Carsten

**Comment by oliverchang** [comment]
Thanks for letting us know! 

Unfamiliar with this AV engine, but would codesigning prevent this from getting flagged?

**Comment by ckrueger1979** [comment]
It improves chances that the file is not flagged.
A valid signature may increase trust in the binary

Google OSV scanner signed by Google maybe not flagged by Google AV :-)

**Comment by another-rex** [comment]
The Google AV engine is no longer flagging out windows binary, though it's still being flagged by Cynet and MaxSecure for some reason.
