### ISSUE TITLE
Dockerfile is not working when I run it after building it

### ISSUE THREAD

**Issue by m8nt0** [google/osv-scanner#1111]
At first I run "docker build -t osv-scanner .
[+] Building 46.7s (18/18) FINISHED                                                          docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                         0.0s
 => => transferring dockerfile: 1.82kB                                                                       0.0s
 => [internal] load metadata for docker.io/library/golang:1.22.4-alpine3.19@sha256:c46c4609d3cc74a149347161  0.0s
 => [internal] load metadata for docker.io/library/alpine:3.20@sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb71  0.0s
 => [internal] load .dockerignore                                                                            0.0s
 => => transferring context: 79B                                                                             0.0s
 => [builder 1/8] FROM docker.io/library/golang:1.22.4-alpine3.19@sha256:c46c4609d3cc74a149347161fc277e1151  0.0s
 => [stage-1 1/4] FROM docker.io/library/alpine:3.20@sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb7188438f7095  0.0s
 => [internal] load build context                                                                            5.6s
 => => transferring context: 81.59kB                                                                         5.6s
 => CACHED [builder 2/8] WORKDIR /src                                                                        0.0s
 => [builder 3/8] COPY . .                                                                                   0.4s
 => [builder 4/8] RUN go mod download                                                                       20.4s
 => [builder 5/8] RUN apk add --no-cache bash                                                                1.1s
 => [builder 6/8] RUN chmod +x ./scripts/build.sh                                                            0.3s
 => [builder 7/8] RUN ./scripts/build.sh                                                                    18.2s
 => [builder 8/8] RUN go build -o osv-scanner ./cmd/osv-scanner/                                             0.6s
 => CACHED [stage-1 2/4] RUN apk --no-cache add ca-certificates git &&   git config --global --add safe.dir  0.0s
 => CACHED [stage-1 3/4] WORKDIR /root/                                                                      0.0s
 => CACHED [stage-1 4/4] COPY --from=builder /src/osv-scanner .                                              0.0s
 => exporting to image                                                                                       0.0s
 => => exporting layers                                                                                      0.0s
 => => writing image sha256:b7f49dc0042aa9439c2a698687ddd946014a8cc2cf12e9855e780d271b1d9948                 0.0s
 => => naming to docker.io/library/osv-scanner                                                               0.0s"

THEN...

docker run -it osv-scanner   
No package sources found, --help for usage information.

I dont understand why it says "NO PACKAGE sources found". Am i missing something else?

**Comment by another-rex** [comment]
You need to target a directory for it to scan, An example would be:
```
docker run -v /path/to/your/local/project:/mnt osv-scanner -r /mnt
```

This will mount /path/to/your/local/project on your host machine to /mnt, and then perform a recursive scan on it.
