### ISSUE TITLE
Add vulnerabilities.ignore flag to just ignore vulnerabilties.

### ISSUE THREAD

**Issue by another-rex** [google/osv-scanner#1226]
~~the `PackageOveride.ignore` field is ambiguous as to whether license scanning is still performed. Solution could be to rename `ignore` to `ignoreVulns`.~~

Ignore flag already ignores both vulnerabilities and license violations. We should have a second flag for just vulnerabilities. The opposite of #1124

**Comment by G-Rath** [comment]
I thought that `ignore` had it ignored from both license scanning and vulnerabilities?

fwiw, I'd recommend doing something like `vulnerabilities.ignore` to mirror `license.overrides`

**Comment by another-rex** [comment]
Huh you are right, I am just very confused at the behavior of our configs. I'll update this issue to be to introduce a just ignore vulns option.
