### ISSUE TITLE
Accept other names for requirements.txt files or provide a way to specify an extractor

### ISSUE THREAD

**Issue by lengau** [google/osv-scanner#1266]
I would expect the following command to work, extracting a Python `requirements.txt` type file:

```
$ osv-scanner scan --lockfile requirements-dev.txt
```

Instead it says "could not determine extractor".

**Comment by G-Rath** [comment]
This is possible by providing [the name of the extractor separated with a colon](https://google.github.io/osv-scanner/usage/#specify-lockfiles):

```
$ osv-scanner scan --lockfile requirements.txt:requirements-dev.txt
```

**Comment by oliverchang** [comment]
Should we see if we can loosen up some of the detection here to filenames with variations of `*requirements*txt` ? 

@another-rex

**Comment by oliverchang** [comment]
@lengau do you have a list of filenames where you'd expect this to work?

**Comment by G-Rath** [comment]
@oliverchang I thought we'd decided not to support alternative names given how many variations there are in the wild, and that the colon syntax was meant to enable exactly this situation...

Also see #370 and #67 which this duplicates

**Comment by oliverchang** [comment]
Yeah, but given that this has come back time and time again, I think we should revisit this to see if we can offer something better out of the box.
