### ISSUE TITLE
Finds less packages in offline mode

### ISSUE THREAD

**Issue by cepxeo** [google/osv-scanner#1305]
Hello, I'm testing the offline dependency check mode and came across weird behavior when scanner finds less packages from the same pom.xml when in offline mode. Using public Java vulnerable image for it:

```
git clone https://github.com/ScaleSec/vulnado && cd vulnado
```

Found 41 packages in pom.xml:

```
docker run -v ${PWD}:/src --rm ghcr.io/google/osv-scanner /src
Scanning dir /src
Scanning /src/ at commit 53336e14a40a0b25acdb8edd8b65a813e5f61bda
Scanned /src/pom.xml file and found 41 packages
```

And only 8 in offline mode:

```
docker run -v ${PWD}:/src --rm ghcr.io/google/osv-scan
ner --experimental-offline --experimental-download-offline-databases /src
Scanning dir /src
Scanned /src/pom.xml file and found 8 packages
```

**Comment by cuixq** [comment]
Hi @cepxeo this is the expected behaviour - we perform [transitive scanning](https://google.github.io/osv-scanner/supported-languages-and-lockfiles/#transitive-dependency-scanning) for Maven pom.xml, but this is disabled in offline mode.

**Comment by cepxeo** [comment]
Understood - many thanks!
