### ISSUE TITLE
Add Red Hat version comparison support

### ISSUE THREAD

**Issue by hogo6002** [google/osv-scanner#1336]
Following osv.dev's recent addition of support for [RPM versions](https://github.com/google/osv.dev/blob/master/osv/third_party/univers/rpm.py), osv-scanner should also add a `version-rmp.go` file in [internal/semantic](https://github.com/google/osv-scanner/tree/main/internal/semantic) to support Red Hat version comparison.

**Comment by G-Rath** [comment]
It looks like RedHat [isn't available on production yet](https://github.com/google/osv.dev/pull/2735), so there's not `all.zip db available which is needed to write a fixtures generator, and it doesn't seem like there's a staging equivalent of the bucket.

Strictly speaking that shouldn't block this but it would be great to have if possible (and in particular I'm primarily wondering if it could be possible for someone to get a one-time `all.zip` from staging?)

**Comment by hogo6002** [comment]
> It looks like RedHat [isn't available on production yet](https://github.com/google/osv.dev/pull/2735), so there's not `all.zip db available which is needed to write a fixtures generator, and it doesn't seem like there's a staging equivalent of the bucket.

Rocky Linux is based on Red Hat, I think we can use its `all.zip` first to generate fixtures.  We can also use `all.zip` from AlmaLinux and SUSE.

**Comment by another-rex** [comment]
> it doesn't seem like there's a staging equivalent of the bucket.

We do have a private one for the staging environment, I added you as a viewer to it now: Should be able to download the all.zip here: https://storage.mtls.cloud.google.com/osv-test-vulnerabilities/Red%20Hat/all.zip
