### ISSUE TITLE
Incorrect field name for "source" in OSV Scanner Results JSON Documentation

### ISSUE THREAD

**Issue by janniclas** [google/osv-scanner#1391]
The example JSON in the [output documentation ](https://google.github.io/osv-scanner/output/#json) lists a field called `packageSource` (see linked markdown below).
https://github.com/google/osv-scanner/blob/581d1a379c93b0171800317aa8055a65bd6cb364/docs/output.md#L108

However, the actual output I produce with the scanner and what I understand from the code (see linked code part below) the field name should be `source`.
https://github.com/google/osv-scanner/blob/581d1a379c93b0171800317aa8055a65bd6cb364/pkg/models/results.go#L89

I'm happy to create a PR for this if you confirm that this is indeed a typo :)

**Comment by michaelkedar** [comment]
Oh wow, apparently that was changed [ages ago](https://github.com/google/osv-scanner/pull/33/files?w=0#diff-509ebd234fd730f5baf05bda6a9792008d24c949eebd1bc7f696105918674464L50-R80) and we never updated the example documentation (and I guess never updated that example output).

So yes - that's a mistake in the docs :)
