### ISSUE TITLE
Do mutliple BatchQueries requests in parallel

### ISSUE THREAD

**Issue by michaelkedar** [google/osv-scanner#1411]
BatchQueries have to be chunked into groups of 1000 packages per request.
We currently make each chunked BatchQuery sequentially:
https://github.com/google/osv-scanner/blob/8d59ca5d95eca2b5c3b5cb4cb0d519fd468b3129/pkg/osv/osv.go#L185-L191

We could get a decent performance improvement on large scans if we do these in parallel, though we might want to make sure the OSV API is okay with these kinds of spikes.

**Comment by oliverchang** [comment]
@hogo6002 putting this in your queue in case you're ever blocked waiting on other things :)
