### ISSUE TITLE
[GitHub Action] Call analysis doesn't work for go projects with go version > 1.22.8

### ISSUE THREAD

**Issue by shahar-h** [google/osv-scanner#1453]
Currently call analysis doesn't work for go projects with go version > 1.22.8, which is the go version of the latest `osv-scanner-action` image (v1.9.1).
When a new vulnerability is detected call analysis fails with:
```log
Failed to run code analysis (govulncheck) on '/app/tools/src/buf/go.mod' because govulncheck: loading packages: err: exit status 1: stderr: go: go.mod requires go >= 1.23.3 (running go 1.22.8; GOTOOLCHAIN=local)

(the Go toolchain is required)
```

I suggest one of the following:
1. Release a new osv-scanner version and osv-scanner-action version when a new golang version is available. Currently there is an open [PR](https://github.com/google/osv-scanner/pull/1431) with alpine based image update, which also updates go version to latest.
2. Add support in github action to install and run `osv-scanner` on machine instead of inside container, thus allowing the consumer to install go itself, similar to [golangci-lint-action](https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#how-to-use).

Can you please merge the PR for now and release a new version?

**Comment by another-rex** [comment]
Good idea to support using the host osv-scanner rather than fully relying on a containerised version. We'll release a new version of osv-scanner soon to fix the govulncheck issue as well.

**Comment by hogo6002** [comment]
We have made a fix release for this issue: https://github.com/google/osv-scanner/releases/tag/v1.9.2
