### ISSUE TITLE
Support multiple packages in one .spdx

### ISSUE THREAD

**Issue by 0x4bit** [google/osv-scanner#169]
First: a nice and very helpful project. Thanks for that.

The Subject: I have a .spdx (tagged, not json) with multiple packages. The first one is quite large (>200k lines) and doesn't have PURLs. Following packages does contain PURLs.
When I run osv-scanner -S big.spdx I get "No package sources found, --help for usage information."

Then I removed the first package from the .spdx and rerun the command osv-scanner -S small.spdx. Now I get findings.

I suspect, that osv-scanner either does not scan multiple packages successively or stops on the first one that doesn't contain PURLs.

**Comment by pombredanne** [comment]
@0x4bit  which tool did you use to create this?

**Comment by 0x4bit** [comment]
I didn't create the SPDX. I've searched for real world examples and found that Kubernetes releases their SBOM with each release. The one I used is for version 1.26.0 (Link: https://sbom.k8s.io/v1.26.0/source).
The modification I did during testing was removing the '##### Package: kubernetes' part - so everything lines 11-260500

**Comment by oliverchang** [comment]
Thanks for filing an issue! 

It seems like this might be because our parsing supports SPDX 2.2, but this document is in 2.3 format. IT should be an easy fix on our side, but I wonder if the SPDX 2.3 parser is backwards compatible. i.e. can it parse all SPDX 2.2 documents, or will we have to support it separately?

**Comment by oliverchang** [comment]
Looking at https://github.com/spdx/spdx-spec/issues/83#issuecomment-388078634

and https://spdx.github.io/spdx-spec/v2.3/diffs-from-previous-editions/ it looks like it should be backwards compatible.

That said, I did also notice that there are [additional package manager type](https://spdx.github.io/spdx-spec/v2.3/external-repository-identifiers/#f3-package-manager)s that we don't support (e.g. "npm"). we'll track that in a new bug.
