### ISSUE TITLE
GitHub Action action.yml error

### ISSUE THREAD

**Issue by Neko7sora** [google/osv-scanner#170]
`https://github.com/KamePowerWorld/www.kamesuta.com/actions/runs/4025482755/jobs/6918755420`
```
Error: google/osv-scanner/e569787b37455a4c55ca02829efd2f25734a5894/action.yml (Line: 17, Col: 10):
Error: google/osv-scanner/e569787b37455a4c55ca02829efd2f25734a5894/action.yml (Line: 17, Col: 10): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.version
Error: Fail to load google/osv-scanner/e569787b37455a4c55ca02829efd2f25734a5894/action.yml
```

https://github.com/google/osv-scanner/blob/e569787b37455a4c55ca02829efd2f25734a5894/action.yml#L8-L10

```diff
  version:
    description: 'osv-scanner version to use'
    required: true
+    default: 'latest'
```

**Comment by G-Rath** [comment]
I assume you're getting at the fact that [`required` doesn't actually make inputs required](https://github.com/actions/runner/issues/1070) in GitHub Actions, and so you're suggesting the action defaults to `latest`.

**Comment by oliverchang** [comment]
Hi! 

Thanks for trying this. Note that our GitHub action is not ready for use yet and is tracked as part of #57.

@another-rex should we make it clearer somehow that this is not ready for use?

**Comment by oliverchang** [comment]
Closing this in favour of tracking overall process in #57.
