### ISSUE TITLE
BUG-The requirements.txt file of the Python project is not recognized

### ISSUE THREAD

**Issue by coffeehb** [google/osv-scanner#194]
osv-scanner version: 1.1.0
commit: a6c6cd756e0cf4fd858398976208145cb23e707b
built at: 2023-01-12T03:38:42Z

when i run like this:
`osv-scanner --lockfile 'requirements.txt:/Users/XXX/Desktop/requeriments.txt'`

the error like:
`could not determine parser for /Users/XXX/Desktop/requirements.txt:/Users/XXX/Desktop/requeriments.txt`

**Comment by G-Rath** [comment]
This is because this feature was recently landed, and not yet released - I've opened #194 adding a note to the readme about this.
