### ISSUE TITLE
Don't include upcoming features in main README

### ISSUE THREAD

**Issue by oliverchang** [google/osv-scanner#196]
Currently the main README includes details of unreleased features. We should only show the README from the current release.

**Comment by oliverchang** [comment]
Thanks for the head's up @G-Rath. 

I've temporarily created a `last-stable` branch for now and made that the main branch to avoid confusion from new users.

This is not ideal (new PRs will be opened against this by default instead), but for now I can't think of another clean/easy fix.

@another-rex WDYT?

**Comment by oliverchang** [comment]
Longer term we probably want to move the docs into a dedicated rendered site, and reduce the amount of detailed documentation in the main README.

**Comment by another-rex** [comment]
This is probably the best option for now, in the slightly longer term @hayleycd's suggestion to move the actual usage instructions from the README over to it's own static site / github page should resolve this fully.

**Comment by another-rex** [comment]
Well, since moving instructions to it's own page is the plan, maybe for now it'll be less disruptive if we set the default back to main, and add a note to check out the last-stable branch readme for usage instructions, and that main has unreleased changes (e.g. #195)

**Comment by oliverchang** [comment]
Good point: we can have a lighterweight hybrid approach for now. I think we can:

1. Reduce the root README.md to be the bare minimum, and move the bulk of the documentation to a USAGE.md or something similar. 
2. Point to the last-stable `USAGE.md` in the main README.md. There is a chicken and egg in that `USAGE.md` doesn't exist for `last-stable` currently. For now we can just point it to the main `README.md`, and fix things up next release.

**Comment by oliverchang** [comment]
@another-rex, if this sounds good to you, I'll assign this to you :)

**Comment by hayleycd** [comment]
I've actually done a fair amount of the work to move the docs to a github page, we could have it up soon. We can build the github page from whatever branch you like. We can add to the docs on main, moving over changes to the stable branch when ready.

**Comment by hayleycd** [comment]
I'm fine with the approach. I'm just letting you know we could have a page ready in a couple of days.

**Comment by oliverchang** [comment]
SG! Let's get this quick fix in now, and then move over to the proper documentation site. Thanks a ton @hayleycd !!

**Comment by another-rex** [comment]
Fixed by moving documentation to github page in #201
