### ISSUE TITLE
Results unclear when no vulnerabilities are found. 

### ISSUE THREAD

**Issue by hayleycd** [google/osv-scanner#237]
When a repository is scanned but no vulnerabilities are found, the scanner does not give you any indication that the process successfully completed. 

No results are displayed, but it isn't immediately clear if that is because no vulnerabilities were found or if something went wrong while scanning the project. 

I would expect to see a one line note saying something along the lines of "No vulnerabilities were found in your project." And perhaps have it output in green. 

I recently scanned my copy of the osv-scanner project and there were no results returned. I wasn't sure what had happened until I ran it again with json output and it returned an empty result.

**Comment by G-Rath** [comment]
Can you provide more details about your project and how you called the scanner? Having no output at all means that nothing was scanned as the scanner should [output the directories and files it scanned](https://github.com/google/osv-scanner/blob/main/cmd/osv-scanner/main_test.go#L148-L159), however [that should result in an error](https://github.com/google/osv-scanner/blob/main/cmd/osv-scanner/main_test.go#L104-L112).

**Comment by hayleycd** [comment]
These are the last two lines that print out when I run it for a project that doesn't return any vulnerabilities. 

`Scanned /usr/local/google/home/denbraver/code/osv-scanner/docs/Gemfile.lock file and found 89 packages
Scanned /usr/local/google/home/denbraver/code/osv-scanner/go.mod file and found 36 packages`

So it is clear that it is scanning the repo and finding packages, but I would expect it to then say something like. 

`No vulnerabilities found`

When I scan the same repo with `--output json` this is what I get:

`Scanned /usr/local/google/home/denbraver/code/osv-scanner/docs/Gemfile.lock file and found 89 packages
Scanned /usr/local/google/home/denbraver/code/osv-scanner/go.mod file and found 36 packages
{
  "results": []
}
`

**Comment by G-Rath** [comment]
Ok cool - I don't disagree with you, but just that is different from "these was no output" :)

**Comment by hayleycd** [comment]
Agreed. I tried to get at that by saying "no results are displayed" in that first comment. Changed the name of the issue for clarity.
