### ISSUE TITLE
Update documentation on how to scan local Debian/Ubuntu OS

### ISSUE THREAD

**Issue by KoenDG** [google/osv-scanner#271]
The documentation here: https://google.github.io/osv-scanner/usage/

Claims this is a preview and doesn't describe how to do it, skipping to the scanning of Docker containers.

Looking at the code a bit, it's not clear to me how it would be done.

**Comment by hayleycd** [comment]
Thank you for opening an issue. We'll look into it.

**Comment by another-rex** [comment]
I believe this is resolved in the documentation here: https://google.github.io/osv-scanner/supported-languages-and-lockfiles/#alpine-package-keeper-and-debian-package-manager

Essentially, you have to specify the lockfile type:
```
osv-scanner --lockfile 'apk-installed:/lib/apk/db/installed'
```
