### ISSUE TITLE
All output goes to stdout when format is json

### ISSUE THREAD

**Issue by tepentti** [google/osv-scanner#274]
I would like to pipe the json output of the tool to a json parser. This is not currently possible since all of the output, including error messages and messages like "Scanning dir /src", are written to stdout. Could it be possible to write the json output to stdout and other messages to stderror?

**Comment by G-Rath** [comment]
That should already be the case 🤔 can you confirm what command you're running?

**Comment by tepentti** [comment]
Sorry, i now know why. I'm running it on docker and obviously all the output from the container is to stdout. Sorry about the false issue.

**Comment by JR-Utily** [comment]
In fact I think this is a real issue, even if only happening with docker.

I'd suggest we should have a -o option to write output file, so we can for example:

```
docker run -it -v ${PWD}:/src ghcr.io/google/osv-scanner --json -L /src/go.mod -o /src/vulnerabilities.osv.json
```

At the moment, the output results are not usable if using docker.

**Comment by another-rex** [comment]
@JR-Utily Good news! We do have that option, `--output <path>` will save the output to a file.

**Comment by JR-Utily** [comment]
Fantastic !
So maybe it should be mentioned on https://google.github.io/osv-scanner/output/ so people know about it ?
Thanks a lot !

**Comment by another-rex** [comment]
Good point, created #593 to add it into the web docs.
