### ISSUE TITLE
ParseMavenLock hangs when parsing some Maven archetypes files

### ISSUE THREAD

**Issue by spencerschrock** [google/osv-scanner#293]
Both of these small `pom.xml` files seem to cause `osv-scanner` to hang. One invocation ran for 5+ hours before the program was terminated for other reasons.

Reproducible with:
```
osv-scanner -L ./pom.xml
```

https://github.com/Open-Wide/owsi-nuxeo-boilerplate/blob/96a65826d8f610d17b269d0da1d577bbb5d46cb1/archetype/src/main/resources/archetype-resources/pom.xml

https://github.com/BeOne-PL/promena/blob/adbc25d2cd3acf1990f7188938fee25d834aa0db/sdk/promena-transformer/promena-transformer-archetype/src/main/resources/archetype-resources/configuration/pom.xml

**Comment by G-Rath** [comment]
Looks like it's because these are technically invalid XML - not sure why it doesn't just crash though; might require implementing a custom parser to properly support 🤔

**Comment by spencerschrock** [comment]
Do you know if this is a problem with `encoding/xml`, or with `func (p *MavenLockProperties) UnmarshalXML`?

My profiler seemed to end up in a loop with the latter

**Comment by G-Rath** [comment]
Yup doesn't surprise me that the problem is there

**Comment by spencerschrock** [comment]
Knowing that it's invalid XML helped narrow it down.
Adding some logic to handle the error that `d.Token` returns here seems to break the loop. 
https://github.com/google/osv-scanner/blob/96a62e9124d34cf738d3314de4d85218677ed4e1/pkg/lockfile/parse-maven-lock.go#L75-L81

Let me know if you'd prefer to handle it, or I can send a PR.

**Comment by G-Rath** [comment]
I've got about half a day of work left before I can look into this more deeply, so if you're ready to do a PR right now go for it
