### ISSUE TITLE
Provenance is archived with zip in v1.3.1

### ISSUE THREAD

**Issue by suzuki-shunsuke** [google/osv-scanner#323]
https://github.com/google/osv-scanner/releases/tag/v1.3.1

In the release v1.3.1, the provenance was archived with zip.

[multiple.intoto.jsonl.zip](https://github.com/google/osv-scanner/releases/download/v1.3.1/multiple.intoto.jsonl.zip)

<img width="351" alt="image" src="https://user-images.githubusercontent.com/13323303/229098880-a17719d7-d3cd-455d-ba70-2268d8e2d858.png">

On the other hand, in previous versions provenances weren't archived.

e.g. v1.3.0: [multiple.intoto.jsonl](https://github.com/google/osv-scanner/releases/download/v1.3.0/multiple.intoto.jsonl)

So to verify the artifact with the provenance, you have to unarchive the zip file.
This is s a bit inconvenient and you have to fix the script to install this tool.
The zip file includes only one file, so I don't think we have to archive the provenance.

So how about stopping to archive the provenance?

**Comment by suzuki-shunsuke** [comment]
I checked the log of the release workflow.

https://github.com/google/osv-scanner/actions/runs/4560390888/jobs/8045359739#step:4:25

> Artifact multiple.intoto.jsonl has been successfully uploaded!

It seems that `multiple.intoto.jsonl` was updated. 🤔

**Comment by another-rex** [comment]
Thanks for pointing this out! I updated the release to extract the zip now.

Because of the new release process we have to manually upload the provenance data for now until https://github.com/slsa-framework/slsa-github-generator/issues/1476 is resolved, which caused the zip to be uploaded.
