### ISSUE TITLE
SPDX parsing improvements

### ISSUE THREAD

**Issue by oliverchang** [google/osv-scanner#335]
Tracking bug for a number of improvements to our current SPDX parsing

- [ ] We should warn with a more specific error message when there are no PURLs available in the SBOM.
- [x] Currently for passing SPDX JSON files to `-L` we expect ".spdx.json" in the filename. Otherwise we will silently report that there are no packages. We should be more flexible here since we've seen a few instances/complaints for this.  
- [x] We don't propagate detailed errors messages back to the user when a malformed SPDX file is provided (https://github.com/google/osv-scanner/blob/cfaf9f8205ac0e2a8f1fb93ea792bc648831d0fd/internal/sbom/spdx.go#L66)

**Comment by anotherbridge** [comment]
@oliverchang For your second point I would suggest that first an appropriate error message should be placed, since if the tool reports that no packages were found the first point one would think of is that something within the SBOM is incorrect and not that the filename is non conformant.

**Comment by oliverchang** [comment]
Thanks @anotherbridge. We're actually going to be more relaxed on the filenames here (in https://github.com/google/osv-scanner/pull/339) to make the scanner easier to use. Point 3 in this bug (more detailed parsing errors) was also implemented.

This should go out in our next release.
