### ISSUE TITLE
misleading document or code implementation

### ISSUE THREAD

**Issue by trganda** [google/osv-scanner#347]
As the document example from [specify-sbom](https://google.github.io/osv-scanner/usage/#specify-sbom),

We can specific the sbom file to osv-scanner.

```
osv-scanner --sbom=/path/to/your/sbom.json
```

But the code from v1.3.1, [func (c *CycloneDX) MatchesRecognizedFileNames(path string) bool](https://github.com/google/osv-scanner/blob/v1.3.1/internal/sbom/cyclonedx.go#L25) was expected the file name like

```go
expectedGlobs := []string{
  "bom.xml",
  "bom.json",
  "*.cdx.json",
  "*.cdx.xml",
}
```

May be we should update the use case of document or re-implement the `MatchesRecognizedFileNames`

**Comment by another-rex** [comment]
Thanks for pointing this out, you're right the documentation is outdated/misleading for v1.3.1, I'll create a PR to fix this.

Though FYI recently #339 was merged which will relax the code implementation so that the example in the documentation will be correct again in the next release.

**Comment by trganda** [comment]
That's good, hope the tools be better.😃
