### ISSUE TITLE
Add option to disable color in default table output

### ISSUE THREAD

**Issue by inkel** [google/osv-scanner#376]
Hi! First and foremost, great tool!

I'm not a cool guy and I use a light theme on my terminal (solarized light, in fact) and when running the tool it looks completely ilegible:

<img width="1070" alt="Screenshot 2023-05-11 at 10 50 31" src="https://github.com/google/osv-scanner/assets/108421/10d43826-990e-4f0f-9ac9-fa92d9f707a1">

I had to switch to a dark background terminal in order to know which vulnerabilities the tool found:

<img width="877" alt="Screenshot 2023-05-11 at 10 50 54" src="https://github.com/google/osv-scanner/assets/108421/32f0a6ef-1eac-4dbd-9566-fbbafdcf0632">

I believe it would be great if any of the following gets implemented:

- detecting terminal style and use the right kind of colors
- disable colored output by default (`--color=false` flag maybe?)
- add a configuration option for colored output

What do you think? I would be willing to try and implement any of the solutions, or listen to other ones! Thanks!

**Comment by another-rex** [comment]
Thanks for bringing this up, I think having a flag to disable the coloured output is a good idea, though I initially added coloured output to help differentiate each line clearly in the table without having to put in an extra line in between, so we might need to add those lines back when colour's disabled.

**Comment by another-rex** [comment]
A workaround for now to disable color output is to pipe osv-scanner's output into something else e.g. `cat`
```
osv-scanner -r ./my-project/ | cat
```

**Comment by spencerschrock** [comment]
+1, some of the colors are unreadable without highlighting. I believe the second row in my screenshot has black background and black font.
<img width="866" alt="Screenshot 2023-09-05 at 11 08 54 AM" src="https://github.com/google/osv-scanner/assets/6064089/1b443c32-5c1d-42ca-8e78-3098e656c6ed">




> A workaround for now to disable color output is to pipe osv-scanner's output into something else e.g. `cat`
> 
> ```
> osv-scanner -r ./my-project/ | cat
> ```

Thanks for the workaround, this also makes the table more copy-paste friendly for Markdown. It still need a find/replace for`+` to `|` at the intersection, but that's less steps than the native output. `cat` must do some of the conversion between:
* `─` (0x2500) and `-` (0x2D)
* `│` (0x2502) and `|` (0x7C)
* all of the box arc/corners (0x256D - 0x2570) to `+`

**Comment by G-Rath** [comment]
This isn't meant as a plug, but would folks mind checking the output of [`osv-detector`](https://github.com/G-Rath/osv-detector)? We've been talking about bring its more vertical-based output over to the scanner, and it would be good to know how the colors being used there fair

**Comment by spencerschrock** [comment]
> This isn't meant as a plug, but would folks mind checking the output of [`osv-detector`](https://github.com/G-Rath/osv-detector)? We've been talking about bringing its more vertical-based output over to the scanner, and it would be good to know how the colors being used in that output fair

I know why it's like this on the Go and GitHub side, but GitHub's capitalization in the address bar is a mild inconvenience here haha.
```console
$ go install github.com/G-Rath/osv-detector@latest
go: github.com/G-Rath/osv-detector@latest: version constraints conflict:
	github.com/G-Rath/osv-detector@v0.11.2: parsing go.mod:
	module declares its path as: github.com/g-rath/osv-detector
	        but was required as: github.com/G-Rath/osv-detector
```

Color-wise, I have no complaints. I think the problem with osv-scanner's coloring is the background color it inserts for the rows, which `osv-detector` doesn't do.

Output-wise, I like having a table sometimes for Markdown purposes, but I can always do `--format table` if the default format changes.

**Comment by another-rex** [comment]
> +1, some of the colors are unreadable without highlighting. I believe the second row in my screenshot has black background and black font. <img alt="Screenshot 2023-09-05 at 11 08 54 AM" width="866" src="https://user-images.githubusercontent.com/6064089/265787867-1b443c32-5c1d-42ca-8e78-3098e656c6ed.png">
> 
> > A workaround for now to disable color output is to pipe osv-scanner's output into something else e.g. `cat`
> > ```
> > osv-scanner -r ./my-project/ | cat
> > ```
> 
> Thanks for the workaround, this also makes the table more copy-paste friendly for Markdown. It still need a find/replace for`+` to `|` at the intersection, but that's less steps than the native output. `cat` must do some of the conversion between:
> 
> * `─` (0x2500) and `-` (0x2D)
> * `│` (0x2502) and `|` (0x7C)
> * all of the box arc/corners (0x256D - 0x2570) to `+`

`cat` doesn't do the conversion, we disable the unicode output when piping to a non terminal output (e.g. to a file for example). 

If you are looking for a markdown output, you can just pass `--format=markdown` to get a markdown table directly. See https://google.github.io/osv-scanner/output/#markdown-table

**Comment by Dor1s** [comment]
+1, I also got confused by dark font on with dark background.
![osv-scanner-output](https://github.com/google/osv-scanner/assets/3372458/1fe3ccef-ed13-4752-9a9b-9623958ebecc)
