### ISSUE TITLE
Gitignore parsing iterates through all directories unnecessarily

### ISSUE THREAD

**Issue by another-rex** [google/osv-scanner#389]
The git ignore parsing logic *always* iterates down through all directories, even ignored directories. 

This causes scans that don't use the -r flag to take a surprisingly long time to complete, and also causes large, directory structures that have been ignored to take a long time to scan, since those directories are walked through to find ignore files.

**Comment by robotdana** [comment]
i can take a look at this

**Comment by robramsaynz** [comment]
Can you assign this to me please @another-rex
