### ISSUE TITLE
Failed to parse SBOM using all supported formates.

### ISSUE THREAD

**Issue by Huiicat** [google/osv-scanner#396]
Hello,

We use Microsoft sbom-tool to generate the sbom list named `manifest.spdx.json`, the version is `spdx_2.2`.
However, when using `osv-scanner_1.3.3_windows_amd64.exe --sbom manifest.spdx.json`, it comes the error:

```
Failed to parse SBOM using all supported formats:
no Package URLs found:
        scanned C:\Users\CyberSec-LAB\Documents\osv-scanner\manifest.spdx.json as SPDX SBOM, but failed to find any package URLs, this is required to scan SBOMs
failed to parse CycloneDX:
        failed trying json: invalid BOMFormat
        failed trying xml: EOF
No package sources found, --help for usage information.
```

Even I used cyclonedx to convert spdx to sbom, it is still not work.
Does osv-scanner not support the version or can I do something to check more?
Thank you.

**Comment by oliverchang** [comment]
Hi! 

Are you able to share a sample SBOM for us to look at? 

The "but failed to find any package URLs, this is required to scan SBOMs" error also indicates that this may be an SBOM without any package URLs.

**Comment by Huiicat** [comment]
[sbom_sample.zip](https://github.com/google/osv-scanner/files/11570779/sbom_sample.zip)
Hi, thanks for the reply.
Here is an example.
sbom.spdx.json is the original file and sbom.json is the transformed file.

**Comment by Huiicat** [comment]
Hello,

We found the problem is sbom-tool do not support C/C++(only when projecet using CMake can be scanned) and java, so our spdx.json can't generate package URLs.
Sorry for wasting your time, thanks!

**Comment by oliverchang** [comment]
No worries, thanks for following up.
