### ISSUE TITLE
osv-scanner does not catch Go/stdlib vulnerabilities 

### ISSUE THREAD

**Issue by ecktom** [google/osv-scanner#453]
Running `govulncheck` on a repo directly is producing the following results:

```
# govulncheck ./...
Using go1.20.4 and govulncheck@v1.0.0 with vulnerability data from https://vuln.go.dev (last modified 2023-07-27 20:09:46 +0000 UTC).

Scanning your code and 484 packages across 79 dependent modules for known vulnerabilities...

Vulnerability #1: GO-2023-1878
    Insufficient sanitization of Host header in net/http
  More info: https://pkg.go.dev/vuln/GO-2023-1878
  Standard library
    Found in: net/http@go1.20.4
    Fixed in: net/http@go1.20.6
    Example traces found:
     <redacted>

Vulnerability #2: GO-2023-1840
    Unsafe behavior in setuid/setgid binaries in runtime
  More info: https://pkg.go.dev/vuln/GO-2023-1840
  Standard library
    Found in: runtime@go1.20.4
    Fixed in: runtime@go1.20.5
    Example traces found:
      <redacted>
      
Your code is affected by 2 vulnerabilities from the Go standard library.
```

Running `osv-scanner` however does not catch those. The issue here is, that based on https://github.com/google/osv-scanner/blob/93a2ec9f45208209cbfa1df825d94396d7bcf472/internal/sourceanalysis/go.go#L113
`osv-scanner` is producing a fixed set of vulnerabilities based only on the entries from the `go.mod` file. The result get's injected into `govulncheck` as database. However, GO's stdlib dependencies are not listed within `go.mod` and thus will never get found. 

Does it make sense to include everything from stdlib by default? https://osv.dev/list?ecosystem=Go&q=stdlib

**Comment by another-rex** [comment]
Since `go.mod` also includes the go version, I think we can fix this by making go/stdlib a "package" as well, and search osv.dev API for it, which should return the correct results.

**Comment by oliverchang** [comment]
> ~Since `go.mod` also includes the go version, I think we can fix this by making go/stdlib a "package" as well, and search osv.dev API for it, which should return the correct results.~
> 
> Hmm it seems like go.mod doesn't include the patch version, which would make the above fix not that useful.

Hmm, this seems complicated to get right. How do we find for sure which version of Go is used? 
- Is it the `go` binary we find in `PATH` ? Or could multiple versions be installed elsewhere and we would have no idea where? 
-  If we do find a reasonable version from the developer machine, is the `go` version we find the same as the one in production environments?

**Comment by victorazzam** [comment]
What about adding the Go version used to compile osv-scanner into the binary itself? Instead of relying on PATH where there could be naming conflicts and/or version mismatches 🤔

**Comment by ecktom** [comment]
I agree finding out the right version is tricky. 
However, I would argue that it is within the responsibilities of the users to align local and production versions, not only for security reason.
From my perspective, relying on the version from the environment is the best way here. It is also similar to running `govulncheck` directly.
How about adding this as an opt-in feature if you're concerned about a version mismatch?

**Comment by guelfey** [comment]
Agree, just using `go version` with `go` from `PATH` seems like the best option, then whoever runs it has to make sure that this is the "correct" version.

**Comment by oliverchang** [comment]
Thanks for the feedback all, that does make sense. @another-rex WDYT? Is this an easy feature to add to our existing scanning?
