### ISSUE TITLE
to support format with csv

### ISSUE THREAD

**Issue by mvpbang** [google/osv-scanner#470]
# suggest
csv human to sort

PS C:\Users\songjianb\Downloads> .\osv-scanner_1.3.6_windows_amd64.exe -f csv -r D:\gaga-dev\hgzx-web
unsupported output format "csv" - must be one of: "table", "json", "markdown"

**Comment by mvpbang** [comment]
support  output save file

**Comment by another-rex** [comment]
Can you explain what you want to use the CSV output for? We are trying to keep the number of formats we support low to make maintenance easier. 

We currently have the JSON output as the machine readable format, is it possible to use that instead?

**Comment by mvpbang** [comment]
use CSV output to quick sort by excel(for example CVSS、PACKAGE )，json output to good for program。

**Comment by napster-kylegato** [comment]
I too would like CSV output formats, although I understand that I can write something to convert the JSON to CSVs it would be nice to stay native....the reason being vaguely, accountants and auditor requirements.
