### ISSUE TITLE
osv-scanner subcommands

### ISSUE THREAD

**Issue by oliverchang** [google/osv-scanner#478]
We need to introduce a concept of subcommands to OSV-Scanner. e.g.

```
osv-scanner scan ... # with the current set of flags 
osv-scanner update ...
osv-scanner fix ...
```

We should do this in a backwards compatible way -- if no subcommand is specified, we fall back to "scan".

**Comment by oliverchang** [comment]
@hogo6002 this might be an interesting one to design and implement! 

@cuixq @michaelkedar FYI

**Comment by andrewpollock** [comment]
Drive by signal boost of https://clig.dev/
