### ISSUE TITLE
CI/CD integration guide

### ISSUE THREAD

**Issue by andrewpollock** [google/osv-scanner#550]
Inspired by #549 I think an overall integration guide with all of the popular CI/CD pipelines would be a Good Thing to increase adoption.

Potential target lists:
- https://hevodata.com/learn/open-source-ci-cd-tools/
- https://estuary.dev/open-source-ci-cd-tools/

**Comment by oliverchang** [comment]
+1. Let's polish up our GH actions first, and then we can document this.
