### ISSUE TITLE
Extract multiple versions of the same package from pom.xml

### ISSUE THREAD

**Issue by alowayed** [google/osv-scanner#589]
Some `pom.xml` files contain multiple versions of the same package. For example:
```
<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-databind</artifactId>
  <version>2.13.3</version>
</dependency>

<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-databind</artifactId>
  <version>2.13.4</version>
</dependency>

<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-databind</artifactId>
  <version>2.13.4.1</version>
</dependency>
```

Since it's hard to know which will end up being installed / used, it might be best to extract all of them. Currently, only the last package is retained because extraction is keyed on `groupId` and `artifactId`: https://github.com/google/osv-scanner/blob/main/pkg/lockfile/parse-maven-lock.go#L124

**Comment by G-Rath** [comment]
According to [this](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies):

> Note that if two dependency versions are at the same depth in the dependency tree, the first declaration wins.

so we should actually just be picking the first version every time

**Comment by oliverchang** [comment]
> According to [this](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies):
> 
> > Note that if two dependency versions are at the same depth in the dependency tree, the first declaration wins.
> 
> so we should actually just be picking the first version every time

+1. Note though, the `mvn` tool doesn't actually follow this behaviour. The actual implementation seems to take the last specified version, which is consistent with OSV-Scannee

**Comment by cuixq** [comment]
`mvn` also warns about this kind of pom.xml and suggests to fix these problems.

It is also said that future Maven versions might not support building such malformed projects.

**Comment by oliverchang** [comment]
Closing, as it seems that we are following the correct upstream behaviour. 

If anybody disagrees, or discovers that this is perhaps different across different `mvn` versions, please comment here :)
