### ISSUE TITLE
Problemas con la instalacion

### ISSUE THREAD

**Issue by JuanDavRH** [google/osv-scanner#595]
Buenos dias, estoy intentando descargar osv-scanner con una de las siguientes instrucciones:
go install  github.com/google/osv-scanner/tree/main/cmd/osv-scanner@v1
go install github.com/opencontainers/runc@v1

Todo esto desde un script para un pipeline azure, como puedo solucionar? muchas gracias.

**Comment by another-rex** [comment]
See: https://google.github.io/osv-scanner/installation/#install-from-source

You want:
```
go install github.com/google/osv-scanner/cmd/osv-scanner@v1
```

**Comment by JuanDavRH** [comment]
ya tengo instalado go, y estoy usando ese comando desde un pipeline, pero a la hora de digitar el comando osc-scanner para cualquier instruccion, no me funciona, me aparece comando no encontrado, estoy haciendo algo mal en la instalacion o ?

**Comment by another-rex** [comment]
By default it'll be installed to `$HOME/go/bin/osv-scanner`, can you check if you have that path (`$HOME/go/bin/`) in your `$PATH`? 

You can confirm the location it'll be installed in by typing `go env` and looking at `GOPATH=...`, append (`./bin`) to that path and you'll have where `go install` installs to.
