### ISSUE TITLE
SARIF output is missing names on rules breaking GitLab parsing

### ISSUE THREAD

**Issue by jameshartig** [google/osv-scanner#599]
We are using the SARIF output and then converting it to GitLab's own SAST format. One issue we ran into is that GitLab requires a "name" on vulnerabilities which come from the `reportingDescriptor` (rule):
<img width="1317" alt="image" src="https://github.com/google/osv-scanner/assets/112555/9f605e33-4d8b-402b-bb74-de1e1b5c0dce">

GitLab's conversion code just takes the [name field off the rule](https://gitlab.com/gitlab-org/security-products/analyzers/report/-/blob/main/sarif.go?ref_type=heads#L378).

Can the `name` field be added to the rule to fix this?

**Comment by another-rex** [comment]
Thanks for bringing this up! I added the name field, and it will be included in the release this week.
