### ISSUE TITLE
support pre-commit

### ISSUE THREAD

**Issue by Niccolum** [google/osv-scanner#60]
Hello,

Can you support [pre-commit-hook](https://pre-commit.com/) - just add [.pre-commit-hook.yaml](https://pre-commit.com/#creating-new-hooks) to repo and, if possible, use git tags for versioning.

Thanks

**Comment by oliverchang** [comment]
@andrewpollock I think you had thoughts on this before right?

**Comment by andrewpollock** [comment]
Yep, pointed you at my previous thoughts off-issue.
