### ISSUE TITLE
multiple.intoto.jsonl is missing at v1.4.2

### ISSUE THREAD

**Issue by suzuki-shunsuke** [google/osv-scanner#611]
multiple.intoto.jsonl is missing at v1.4.2.

https://github.com/google/osv-scanner/releases/tag/v1.4.2

<img width="393" alt="image" src="https://github.com/google/osv-scanner/assets/13323303/a56a7947-b51e-42e8-b625-d022c77a5888">

Is this expected?
Could you release multiple.intoto.jsonl?

**Comment by another-rex** [comment]
Thanks for pointing this out, it seems to be caused by us changing the release pipeline. I have added it now, but because of https://github.com/slsa-framework/slsa-github-generator/issues/1947 it will not have the tag information, so when verifying, you can't add `--source-tag`.

E.g.
```
> slsa-verifier verify-artifact ./osv-scanner_1.4.2_linux_amd64 --provenance-path multiple.intoto.jsonl --source-uri github.com/google/osv-scanner

Verified signature against tlog entry index 45235995 at URL: https://rekor.sigstore.dev/api/v1/log/entries/24296fb24b8ad77a7c7a96a0f27275410523e36080e7f09bf5da9d938d01894992a94ff893a4a054
Verified build using builder https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.9.0 at commit 137255296e89d6baa9df9c7f7e950a28c1db5c74
PASSED: Verified SLSA provenance
```

**Comment by suzuki-shunsuke** [comment]
Thank you for handling the issue quickly!
I hope the issue will be solved at the next release.
