### ISSUE TITLE
Relax filename requirements for requirements.txt parsing.

### ISSUE THREAD

**Issue by oliverchang** [google/osv-scanner#67]
There is no strict requirement on `requirements.txt`  as the filename for requirements files. We should be able to detect more cases like these.

**Comment by oliverchang** [comment]
This is hard to solve perfectly. Some ideas:

- When passed as a --lockfile argument, assume all "*.txt" files are requirements.txt files.
- When scanning the filesystem, we can make this a bit stricter and require "*requirements*txt" in the filename. Depending on performance, we could potentially also just do all ".txt" files as well.

**Comment by oliverchang** [comment]
@another-rex should we keep this open, or open another one, to better auto-detect additional requirements files?

**Comment by another-rex** [comment]
Let's keep this one open

**Comment by G-Rath** [comment]
>  Another would be to pass in the args the parser, for example --parser=python_requirements

You can already do this by putting the parser you wish to use in front of the file path, seperated with a colon:

```
osv-scanner --config=/Users/pmind/Projects/osv-scanner.toml --lockfile=requirements.txt:requirements/base.txt
```

See [this section of the docs for more](https://google.github.io/osv-scanner/usage/#specify-lockfiles)

> Also it does not manage -r to include another file

Yeah when I initially wrote the `requirements.txt` parser I hadn't decided how they should be supported given they're another file - i.e. should the packages be reported as being from `requirements/production.txt` or `requirements/base.txt`?

Now though I think it should just be treated as if it's all one single file. If you create a new issue for this, I can work on it.

**Comment by pulse-mind** [comment]
Hi @G-Rath ,
It works great with the colon :), thanks a lot. 
```
osv-scanner --config=/Users/pmind/Projects/osv-scanner.toml --lockfile=requirements.txt:requirements/base.txt
```

I created a new issue for nested requirements : https://github.com/google/osv-scanner/issues/252

Best regards,
Fred
