### ISSUE TITLE
enable easy usage in CI

### ISSUE THREAD

**Issue by jdhenke** [google/osv-scanner#7]
I had a CI script that just broke because logs are not sent to stdout when they were not before, I think a change in #3 

```
osv-scanner -r . | tee /tmp/vulns
2022/11/23 18:56:22 Scanning dir .
2022/11/23 18:56:22 Scanning /app/ at commit f187e875250ec11be568d5f00974ebcddba51aa3
2022/11/23 18:56:22 Scanned /app/go.mod file and found 37 packages
! [ -s /tmp/vulns ]
```

This used to exit 0, now it exits 1 because those log lines actually get piped to `/tmp/vulns` so the file is not empty.

How should `osv-scanner` be properly used in CI?

Thanks!

**Comment by another-rex** [comment]
Can you try the `--json` option, which will print all logs to stderr and only put the json output into `/tmp/vulns`. It still won't be empty when there's no vulnerabilities, but will look like:
```
{
  "results": []
}
```

So you will still need another step with a tool like `jq`: `cat /tmp/vulns | jq '.results | length'`, which isn't ideal. 

I think we can improve the CI usage by adding a `--fail-on-vuln` flag similar to other scanners, where if there is a vulnerability, the exit code will be non zero.  What do you think?

**Comment by jdhenke** [comment]
Yep, exiting non-zero when any vulnerabilities are found would be great :+1: 

FWIW, we also use https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck which I believe follows this behavior without needing to specify any additional flags.

**Comment by G-Rath** [comment]
@another-rex I'm happy to do this if you want to assign it to me (it was next on my todo list after #3 was landed)
