### ISSUE TITLE
Option to skip "Upload to code-scanning" step in "osv-scanner-reusable-pr.yml"

### ISSUE THREAD

**Issue by fingeromer** [google/osv-scanner#701]
When using `osv-scanner-reusable-pr.yml` in my project, the action fails due to the next error:
`codeql/upload-sarif action failed: Resource not accessible by integration`

<img width="627" alt="image" src="https://github.com/google/osv-scanner/assets/112797342/6992237f-6590-42d3-933f-a748590a6fbb">

My repo is private and I also don't have Github Advanced Security. 
I would like to use this action only for blocking PR purposes, without using the Security tab features, is that possible?

**Comment by another-rex** [comment]
Thanks for reporting this! I pushed an update that adds an additional input `upload-sarif` which you can pass `false` to to disable uploading to the code-scanning tab. Can you test it out and report if it works for you?

**Comment by fingeromer** [comment]
It skipped! thanks! 
<img width="270" alt="image" src="https://github.com/google/osv-scanner/assets/112797342/a11f65ec-2360-438d-a3d6-6fa03443bc4f">

I suggest adding this argument to your [examples section](<img width="270" alt="image" src="https://github.com/google/osv-scanner/assets/112797342/4ed6b111-1ff1-4b26-bc3f-e70f43e22855">)
