### ISSUE TITLE
Add support for pipenv lock files

### ISSUE THREAD

**Issue by JonZeolla** [google/osv-scanner#71]
Currently `Pipfile.lock` is not a support lock file, please add support.

**Comment by inferno-chromium** [comment]
There is a PR contributed by a community contributor here - https://github.com/google/osv-scanner/pull/66 . It might be 1-2 weeks before it could be merged (due to folks out on holidays, but we will cut a release asap in 2023).

**Comment by JonZeolla** [comment]
@inferno-chromium sounds great.  Would you mind linking the PR to this issue?
