### ISSUE TITLE
Add support for alpine's /lib/apk/db/installed

### ISSUE THREAD

**Issue by kpcyrd** [google/osv-scanner#72]
```
$ osv-scanner --lockfile /lib/apk/db/installed 
could not determine parser for /lib/apk/db/installed
```

It seems osv.dev has [alpine data available](https://osv.dev/list?ecosystem=Alpine) so it seems like a good match. :)

**Comment by questgugou** [comment]
thankyou verymuch

**Comment by cmaritan** [comment]
Hello @questgugou,

In [this](https://github.com/cmaritan/osv-scanner/commit/e7ffc3161df3445592cf9e1ea4149d8c72f41f01) commit I've added support for apk "installed" file.
If you think that it could be OK I can add tests and make a PR.

Regards.
