### ISSUE TITLE
Failed to parse (properly formatted) CycloneDX 1.5 json

### ISSUE THREAD

**Issue by thejan2009** [google/osv-scanner#733]
Hey, according to [the spec](https://cyclonedx.org/docs/1.5/json/#tab-pane_metadata_tools_oneOf_i0), osv-scanner attempts to unmarshal a deprecated format of `metadata.tools` - should be one of `components` or `services`, but it expects a [deprecated array format](https://cyclonedx.org/docs/1.5/json/#tab-pane_metadata_tools_oneOf_i1). This can be reproduced with latest release of `anchore/syft` which outputs the expected new format. 

```
[~] syft packages registry:docker.io/alpine:3.19.0 -o cyclonedx-json=alpine.cdx.json
 ✔ Parsed image                                                                                                                                                                       sha256:1dc785547989b0db1c3cd9949c57574393e69bea98bfe044b0588e24721aa402
 ✔ Cataloged file metadata         [527 locations]
 ✔ Cataloged packages              [16 packages]
 ✔ Cataloged file digests          [840 digests]
[~] osv-scanner --sbom alpine.cdx.json
Failed to parse SBOM using all supported formats:
failed to parse SPDX:
        failed trying json: JSON document does not contain spdxVersion field
        failed trying rdf: found extra chars before tag start
        failed trying tv: unsupported SPDX version: ''
failed to parse CycloneDX:
        failed trying json: json: cannot unmarshal object into Go struct field Metadata.metadata.tools of type []cyclonedx.Tool
        failed trying xml: XML syntax error on line 1: invalid character entity &distro (no semicolon)
No package sources found, --help for usage information.
```

The diff between old and new cyclonedx scan is the following:
``` diff
[~] diff 98.json 99.json
5c5
<   "serialNumber": "urn:uuid:e6b1b429-72b8-488b-b990-af04d52a6a72",
---
>   "serialNumber": "urn:uuid:02b25cda-2ace-468a-9fa9-51514035e167",
8,15c8,18
<     "timestamp": "2024-01-04T07:17:24+01:00",
<     "tools": [
<       {
<         "vendor": "anchore",
<         "name": "syft",
<         "version": "0.98.0"
<       }
<     ],
---
>     "timestamp": "2024-01-04T07:07:25+01:00",
>     "tools": {
>       "components": [
>         {
>           "type": "application",
>           "author": "anchore",
>           "name": "syft",
>           "version": "0.99.0"
>         }
>       ]
>     },
```

**Comment by another-rex** [comment]
I think this has been fixed in https://github.com/google/osv-scanner/pull/718, and will be in our next release. You can try 
```
go install github.com/google/osv-scanner/cmd/osv-scanner@v1.5.1-0.20240102033056-ff7f2d6de2b2
```
or
```
go install github.com/google/osv-scanner/cmd/osv-scanner@main
``` 
to install the latest version on `main` in the mean time.

**Comment by thejan2009** [comment]
Thanks and yes, this is fixed in `main`. Should we keep this issue open in case anybody else has the same problem before the next release?

**Comment by NataliaAn** [comment]
@another-rex Any idea when the next release will happen? Is there a timeline?

**Comment by another-rex** [comment]
> Thanks and yes, this is fixed in `main`. Should we keep this issue open in case anybody else has the same problem before the next release?

Yep, I'll close the issue when the next release is made.

> @another-rex Any idea when the next release will happen? Is there a timeline?

The next release is scheduled for next Wednesday, though we might make the release earlier.

**Comment by NataliaAn** [comment]
Sounds good! Thank you!
