### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [google/osv-scanner#734]
Installation instructions as suggested from https://osv.dev/#use-the-cli don't work.

```
[ec2-user@ip-172-31-9-213 ~]$ go install github.com/google/osv-scanner/cmd/osv-scanner@v1
          
go/pkg/mod/github.com/google/osv-scanner@v1.5.0/pkg/models/results.go:4:2: package slices is not in GOROOT (/usr/lib/golang/src/slices)
note: imported by a module that requires go 1.21
[ec2-user@ip-172-31-9-213 ~]$
```

```
[ec2-user@ip-172-31-9-213 ~]$ go version
go version go1.20.10 linux/amd64
```

```
[ec2-user@ip-172-31-9-213 ~]$ uname -a
Linux ip-172-31-9-213.eu-west-2.compute.internal 6.1.66-91.160.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 13 04:50:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[ec2-user@ip-172-31-9-213 ~]$ 
```

**Comment by another-rex** [comment]
> ```
> imported by a module that requires go 1.21
> [ec2-user@ip-172-31-9-213 ~]$
> ```

We now require 1.21 as the minimum go version to compile osv-scanner. 

If you can't upgrade to 1.21 you can still download the compiled version here: https://github.com/google/osv-scanner/releases, or from any of these package managers: [(full doc here)](https://google.github.io/osv-scanner/installation/)

![PkgManangers](https://repology.org/badge/vertical-allrepos/osv-scanner.svg)
