### ISSUE TITLE
Investigate why main cli tests are so (relatively) slow

### ISSUE THREAD

**Issue by G-Rath** [google/osv-scanner#741]
The test suite has generally been pretty fast as per the nature of Go testing but now it tends to take 30-60 seconds locally with a lot of that time being taken by `github.com/google/osv-scanner/cmd/osv-scanner`.

While that's still relatively fast in the scheme of things, the next slowest package is `semantic` at ~0.200 seconds, _and_ to make it worse the `osv-scanner/cmd/osv-scanner` tests are the most e2e-y, testing the CLI entry function meaning they basically never get to benefit from caching.

I've previously looked into this and I believe it was the result of supporting local databases - in particular, I think one of tests uses the Debian ecosystem which has the latest database by something like a x2 factor; however I didn't explicitly note this anywhere.

Someone should do some digging into what's happening so we have it captured and we can then discuss hopefully how we might be able to make the test(s) faster.

**Comment by G-Rath** [comment]
@billielynch this is for you to pick up

**Comment by billielynch** [comment]
@G-Rath I don't seem to be able to assign myself. Do you want me to be assigned on it now or when I actually have time to look at it?

**Comment by G-Rath** [comment]
@billielynch pretty sure you can only be assigned if you're a collaborator, so for now it'll just have to be unassigned

**Comment by another-rex** [comment]
@billielynch Assigned you to the task now :)

**Comment by billielynch** [comment]
**Confirming the location of the slowness**

Running the tests identifies three files that are taking over 0.1s: 
```
github.com/google/osv-scanner/cmd/osv-scanner   23.991s coverage: 45.4% of statements in ./...
github.com/google/osv-scanner/internal/semantic 0.232s  coverage: 36.8% of statements in ./...
github.com/google/osv-scanner/internal/sourceanalysis   0.960s  coverage: 11.5% of statements in ./...
```
**internal/semantic**
Discussion with @G-Rath indicates that this is just a computationally heavy test group that is doing a lot and fairly optimised already. Going to just pass this one for now.

**cmd/osv-scanner**
[This is by by far the slowest area](https://github.com/google/osv-scanner/blob/main/cmd/osv-scanner/main_test.go). Running each TestRun in `cmd/osv-scanner` we get times: 

- Licenses 2.03s
- LockfileWithExplicitParseAs 1.36s
- GithubActions 1.26s
- SubCommands 0.74s
- LocalDatabases 22.74s

Honing in on the `LocalDatabases` test cases then [here](https://github.com/google/osv-scanner/blob/96b1e4ec731500039e817a10909695ed778a0076/cmd/osv-scanner/main_test.go#L429) as the main culprit. 

I added a time-delta log line, starting with `time: ` [in the `testCli`](https://github.com/google/osv-scanner/blob/96b1e4ec731500039e817a10909695ed778a0076/cmd/osv-scanner/main_test.go#L105) which gives the time for execution for each of the CLI test cases and a log line in the function that [manages the test directories](https://github.com/google/osv-scanner/blob/96b1e4ec731500039e817a10909695ed778a0076/cmd/osv-scanner/main_test.go#L17) starting with `dir: ` recording the used directory.

I also named these tests to help with my sanity and will be using those names a bit going forward. The names are directly related to the fixtures and parameters used.

The output for each set of fixtures and parameters looks like: 
```
RUN   TestRun_LocalDatabases/Locks-Many-with-invalid
    main_test.go:526: dir: /tmp/osv-scanner-test-2947371249
    main_test.go:535: time: 4.161588873s
    main_test.go:536: time: 848.178117ms
```

Things to note are:
- There are two time logs as [each case is run twice](https://github.com/google/osv-scanner/blob/96b1e4ec731500039e817a10909695ed778a0076/cmd/osv-scanner/main_test.go#L520).  
- Each set of params and fixtures runs faster on the second run, this is expected.
- Each set of params and fixtures uses a unique location for its local database, so data is retrieved for each.
- I stopped the tests running parallel while I was doing this investigation, again for my sanity, this results in a blow out of time to ~40s.

From this information I suspect that the time is related to retrieved data. I looked at the directories for each test and created a table like so: 

```
testcase                                                time    size    size:time

TestRun_LocalDatabases/Not-a-Lock                       0.00s   4.0K	~inf
TestRun_LocalDatabases/Json-Single-json                 0.90s   3.4M	~3.8
TestRun_LocalDatabases/Markdown                         0.91s   3.4M	~3.7
TestRun_LocalDatabases/Json_Single-format_json          1.03s   3.4M	~3.2
TestRun_LocalDatabases/Composer-Only                    1.06s   3.4M	~3.3
TestRun_LocalDatabases/Empty-Config-sbom-insecure       4.07s   9.8M    ~2.4
TestRun_LocalDatabases/Nested_Multiple-not-recursive    4.62s   15M     ~3.2
TestRun_LocalDatabases/Locks-Many-with-invalid          5.03s   16M     ~3.1
TestRun_LocalDatabases/GitIgnore-recursive              5.04s   16M     ~3.1
TestRun_LocalDatabases/Nested_Multiple-recursive        5.60s   18M     ~3.2
TestRun_LocalDatabases/GitIgnore-recursive-no-ignore    5.95s   19M     ~3.1
TestRun_LocalDatabases/Locks-Many-all-of-them           8.35s   25M     ~3.0
```

**KEY**
- `time` is test execution time
- `size` is the size of the temp file after a test execution
- `size:time` is size value divided by time value

So the `size:time` value is pretty much exactly my download speed locally and consistent through the tests, with some slower on the faster tests which can be attributed to setup time. 

I dropped my bandwidth on my router to half speed and got an approximate double in test time blow out. I also confirmed the tests are approximately proportionally faster on a faster connection (with other hardware however). **I'm pretty satisfied with concluding that bandwidth on accessing the external resources is the limiting factor with these tests.**

**internal/sourceanalysis**
The vast majority of time in this set of tests is [spent on `Test_RunGoVulnCheck` (0.94s). 
](https://github.com/google/osv-scanner/blob/ed1955649ebd9a167ca68043c96d2223b6044a85/internal/sourceanalysis/integration_test.go#L16). This test runs a scan on a small go module. The test itself has some conditional logic but ultimately is running `runGovulncheck` and checking expected outcome. There is space for further investigation here.

**Comment by G-Rath** [comment]
@billielynch awesome write up - I think it would be good if you could dig into which databases are being downloaded and their approximate sizes for each local test, since some are bigger than others and we might be able to optimize a few by just using different ecosystems for our fixtures.

Beyond that I think there's two main things for us to explore:
  1. "mocking" the databases that get used, probably via a hidden cli flag akin to `--experimental-local-db-path` so that we can then use [`httptest`](https://pkg.go.dev/net/http/httptest) to provide fake databases
      * we're already doing this in other tests which should be very copy-and-paste-able; the downside being it would make things less e2e-dy
  2. allowing reuse of the databases by default, and using `TEST_ACCEPTANCE` (which is enabled in CI) to disable that behaviour

**Comment by billielynch** [comment]
The databases are sized as follows: 

```
system      size
RubyGems    1.1M
Go          2.2M
OSS-Fuzz    2.5M
Packagist   3.4M
Debian      5.3M
Alpine      5.6M
npm         15M
```
As you can see even just not using npm would be helpful :)

**Comment by G-Rath** [comment]
Oh wow yeah the npm database has really grown - it use to be that Debian was the largest 😓

That is probably something we can address - Debian I think is needed for some of the sbom stuff, but pretty sure npm is very generic so could easily be replaced with e.g. composer/packagist

**Comment by G-Rath** [comment]
We've discussed this and decided to explore having the local database tests reuse the local cache when `TEST_ACCEPTANCE` is not set, which should speed these tests up greatly locally.
