### ISSUE TITLE
The latest release download link

### ISSUE THREAD

**Issue by alv2017** [google/osv-scanner#800]
Hi, would like to use osv-scanner in GitLab pipelines. The permalink to the latest release would make my life easier. :) 

Is there a permalink/redirect to the latest software release? 

I'm looking for something like https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64

Thank you!

**Comment by another-rex** [comment]
Ah I see the problem, we publish with the version in the artifact name. I'll look into changing this in the next release.

For now perhaps this one liner could be used to get the latest release (from https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8)
```
curl -s https://api.github.com/repos/google/osv-scanner/releases/latest \
| grep "osv-scanner_.*_linux_amd64" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -
```

Another option is to use our docker image, which is always `ghcr.io/google/osv-scanner:latest` or `ghcr.io/google/osv-scanner-action:latest`

**Comment by alv2017** [comment]
Thank you @another-rex ! :+1: 

Looking forwards to it :)

**Comment by another-rex** [comment]
The latest release now omits the version name from the binary, so your original link should work now :)
