### ISSUE TITLE
Documentation is 404ing

### ISSUE THREAD

**Issue by alex** [google/osv-scanner#812]
https://google.github.io/osv-scanner/ is a 404 for some reason.

**Comment by oliverchang** [comment]
Hmm, looks like the  merge in https://github.com/google/osv-scanner/pull/810 auto-deleted the docs branch :/ 

I've restored it now. FYI @another-rex ! We need some way to avoid this in the future.

**Comment by G-Rath** [comment]
fwiw I'm pretty sure if you just create a branch protection rule that means autodeleting for that branch doesn't happen

**Comment by oliverchang** [comment]
Ah, thanks for pointing to that. I've just created a branch protection setting for the docs branch.

**Comment by jayvdb** [comment]
This can be closed now?
