### ISSUE TITLE
Setting/overwriting license for a dependency

### ISSUE THREAD

**Issue by ststroppel** [google/osv-scanner#814]
Hi, 
I've been exploring the new experimental license scanning feature and find it quite impressive. However, I believe there's a crucial functionality that seems to be missing - the ability to specify the license for a dependency.

During my testing of this feature in our npm repository, I encountered several dependencies where the license information could not be detected due to various reasons:

- The license is not properly specified, resulting in the license being resolved as `UNKNOWN`. An example of this is [khroma](https://www.npmjs.com/package/khroma), where the dependency license is declared as a MIT but it was not retrieved correctly. I suspect the necessary information is missing within the package.json.
- The dependency is published under two or more licenses, requiring the user to select the appropriate one. [type-fest](https://www.npmjs.com/package/type-fest) is an example of this scenario.

Therefore, I propose the addition of a feature that allows users to manually set or overwrite the detected license of a dependency, optionally for a specific version or a version range.

**Comment by oliverchang** [comment]
CC  @josieang

**Comment by arkodg** [comment]
also interested in adopting the license scanning feature in Envoy Gateway, and this issue is stopping us from adopting it at this moment, more in https://github.com/envoyproxy/gateway/issues/2917

**Comment by oliverchang** [comment]
Thanks for the feedback all! 

What would be the most convenient way for you to set this information? 

- A config file? i.e. (https://google.github.io/osv-scanner/configuration/)
- A cmdline flag? e.g. `--license-override=PKG,license` or something similar.

**Comment by ststroppel** [comment]
Thanks @oliverchang for coming back to this topic. For me, definitely a config file would be the most convenient way to set it. There are several advantages for this approach:
- The configuration is stored in the repository and versioned
- Additionally, we could specify some version range as the declared license of a package could change with major releases
- The entries could be enriched by additional meta information like `who` approved the license and `why` (e.g. we have a commercial license for the package, that's why license `abc` is the correct one to be used)

**Comment by oliverchang** [comment]
@josieang (who added the license scanning feature initially) would you have some time to help with implementing this? It would also be a great opportunity to look at moving the feature out of experimental.

**Comment by josieang** [comment]
Thanks everyone for feedback on the license scanning feature! Sorry for missing this thread. I'll have time to work on this in early May.

You may have already seen it, but we have a "How are licenses determined?" section at docs.deps.dev/faq.

@ststroppel Just curious:
> Additionally, we could specify some version range as the declared license of a package could change with major releases
Why only be cautious about license changes only when major version bumps happen? Why not track any license changes for any version bump?

**Comment by shahar-h** [comment]
@ststroppel license can also be changed on minor update, e.g. [terraform](https://github.com/hashicorp/terraform/blob/v1.6.0/LICENSE). In theory it can also be changed on patch update, although I don't think it's a real case. See related discussion: https://github.com/semver/semver/issues/322.
Anyway, I think that users should be able to configure license override for either major/minor/patch versions of a given dependency.

**Comment by josieang** [comment]
Hm, that's an interesting point giving users the option to override on major, minor or patch makes sense to me.

From experience at deps.dev many ecosystems don't fully follow semver and parsing versions properly can be pretty ecosystem-specific.

It's likely guided remediation has needed to figure out how to parse versions, I will chat to @michaelkedar when he gets back from leave. But as a draft PR I'll do something pretty simple like spliting on `.`.

**Comment by G-Rath** [comment]
@josieang I might be able to help with that too if you like - I had to understand how each versions work in each ecosystem as part of creating `semantic`.

That package will probably already have the info you need in order to do the comparisons, it just might not expose them (yet)

**Comment by oliverchang** [comment]
@shahar-h   #949 seems related to this -- Would the same configuration mechanism can be used to handle edge cases like multiple-license vs choice-of-license?

**Comment by shahar-h** [comment]
> @shahar-h #949 seems related to this -- Could the same configuration mechanism be used to handle edge cases like multiple-license vs choice-of-license?

I guess that you should add an override configuration that chooses the desired license in these cases.

**Comment by another-rex** [comment]
This is now possible with the new configuration option in #944. Feel free to reopen if this does not satisfy your use case.
