### ISSUE TITLE
Support C/C++

### ISSUE THREAD

**Issue by oliverchang** [google/osv-scanner#82]
Connect osv-scanner with 

1. https://github.com/google/osv.dev/issues/561
2. https://github.com/google/osv.dev/issues/783

To provide C/C++ dependency detection and vuln management.

**Comment by oliverchang** [comment]
@andrewpollock this would be the logical next step after your work on the NVD coverage!

**Comment by Chronial** [comment]
I don't know if this is the right place for this input. If not, please direct me somewhere else :).

The point of #561 seems to be:
> Given: file hashes
> Return: Repository URL, CPEs, Closest tag/version

For our use case, the input of file hashes would be rather cumbersome. We know our dependencies and their versions – the main problem is effectively mapping these to CPEs. Having an API that takes the library name or source repository URL as input and returns a CPE would be really helpful – or does this already exist?

**Comment by varun-endor** [comment]
@andrewpollock any rough ETA for C/C++ support? Thanks much for working on this btw.

**Comment by andrewpollock** [comment]
@varun-endor it's an end-of-year goal overall, but per https://github.com/google/osv.dev/issues/783#issuecomment-1407906210 I'll break this down into some milestones for interested parties to follow along on.

**Comment by oliverchang** [comment]
The NVD database part is out now! 

The remaining bits for OSV-Scanner support are:
- https://github.com/google/osv-scanner/issues/612
- https://github.com/google/osv-scanner/pull/581

**Comment by andrewpollock** [comment]
I think we can call this "done"?
