### ISSUE TITLE
Improve retry logic to only retry for appropriate HTTP error codes

### ISSUE THREAD

**Issue by another-rex** [google/osv-scanner#861]
Followup to #860 to only retry for appropriate HTTP codes. 

I.e. Only retry on 500s, and not 400 codes

**Comment by shashtag** [comment]
Hello, I would like to work on this issue.

**Comment by shashtag** [comment]
Hello @another-rex , I would like to work on this issue.

**Comment by VishalGawade1** [comment]
Is someone working on this issue? can I have it?

**Comment by another-rex** [comment]
No one is working on this at the moment, but there might be significant refactors coming to the request code as part of our V2 change.  That is still a month or so away though, so plenty of time to get a quick fix in.

**Comment by VishalGawade1** [comment]
Thanks a lot for assigning it to me! I will update you soon :)

**Comment by VishalGawade1** [comment]
Hi @another-rex , I’ve updated the retry logic as discussed, retrying only on 500 errors. Would it be okay for me to raise a PR for this fix? Thanks!

**Comment by G-Rath** [comment]
@VishalGawade1 yup if you've got a fix open a pr 🙂

**Comment by VishalGawade1** [comment]
Hello @G-Rath , @another-rex ,
I have raised a PR, with all the necessary requirements. Please let me know if you have any questions.
