### ISSUE TITLE
Scanning Pseudo Versions of Go

### ISSUE THREAD

**Issue by theinfosecguy** [google/osv-scanner#910]
What's the best possible to scan Pseudo versions in Go?

> A pseudo-version is a specially formatted [pre-release](https://go.dev/ref/mod#glos-pre-release-version) [version](https://go.dev/ref/mod#glos-version) that encodes information about a specific revision in a version control repository. For example, v0.0.0-20191109021931-daa7c04131f5 is a pseudo-version.

Ref: https://go.dev/ref/mod#pseudo-versions

**Comment by oliverchang** [comment]
Hi, 

This should already be supported in OSV-Scanner, because Go pseudoversions are still valid SemVer 2.0 that sort propertly against OSV Go advisories.  

Do you have any cases  where this isn't working for you?

**Comment by theinfosecguy** [comment]
The API seems to return false positives.

**Comment by oliverchang** [comment]
> The API seems to return false positives.

Can you please provide a reproducer so we can investigate?

**Comment by oliverchang** [comment]
Closing due to lack of response! Please comment back if you have a reproducer so we can investigate.
