### ISSUE TITLE
Support for Scala SBT

### ISSUE THREAD

**Issue by LironJit** [google/osv-scanner#921]
Hi :) 
Curious if SBT is anywhere on the roadmap, It'd be super awesome if we could scan `build.sbt` files for dependency vulnerabilities using osv-scanner!
Thanks in advance!

**Comment by oliverchang** [comment]
Hi, thanks for this request.

I don't believe any of us are familiar with Scala or were aware of SBT before. Is there a specific canonical package manager for Scala? Or is this just Maven?  

Contributions are also very welcome :)

**Comment by LironJit** [comment]
Hi @oliverchang, thanks for your quick response! 

SBT is indeed the primary build tool for Scala projects, similar to Maven or Gradle for Java
It uses a file called `build.sbt` to define dependencies. This file is essential for dependency management in Scala projects and can be scanned for vulnerabilities
Unlike Maven, which uses XML, SBT's build files are Scala code

Here's a link to how dependencies are typically mentioned in the `build.sbt` file - https://github.com/sbt/sbt-native-packager/blob/master/build.sbt#L16-L26

**Comment by oliverchang** [comment]
Thanks for the response! My question wasn't phrased well since Maven is a bit of an overloaded term -- it refers to both a package repository protocol and an overall build system/tool.

Do the dependencies specified inside `build.sbt` refer to packages inside a Maven repository? Or are there SBT specific repositories for dependencies? It sounds  like if they refer  to Maven packages, we just need to extract  `"ecosystem": "Maven"` packages from them?

Contributions are also very welcome, if you are able to help with creating a PR for this!

**Comment by Zerkath** [comment]
It is possible to define multiple 'resolvers' for **sbt** https://www.scala-sbt.org/1.x/docs/Resolvers.html similar concept to **maven** repositories https://maven.apache.org/guides/mini/guide-multiple-repositories.html

```sbt
resolvers +=
  "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
```
There is existing tooling for automated CVE scans, but it is not the best. Mostly my problem with it is that it's very slow, 
https://github.com/dependency-check/DependencyCheck

For Scala to check for vulnerable dependencies this is something that could be used. https://github.com/nMoncho/sbt-dependency-check

Similar solution exists for **gradle** https://github.com/dependency-check/dependency-check-gradle

**sbt** & **gradle**  allow for a lot of ways of configuring dependencies. Makes it hard to have unified automation.

For gradle & sbt, maybe it would be possible to render the dependencies to some predictable form.

**sbt** has https://www.scala-sbt.org/2.x/docs/en/reference/sbt-dependency-tree.html
**gradle** has https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html
