### ISSUE TITLE
No package sources found Error when scanning SBOMs

### ISSUE THREAD

**Issue by MFaisalZaki** [google/osv-scanner#93]
I have generated a valid `spdx` file from VCPKG, then I try to use it with `osv-scanner`, but it generates no package sources found.
Can you please help me with this issue?
[vcpkg.spdx.zip](https://github.com/google/osv-scanner/files/10277401/vcpkg.spdx.zip)

**Comment by Rohan-Kar** [comment]
SPDX file format may not be supported . you need to tried with JSON output once .

**Comment by Rohan-Kar** [comment]
> I have generated a valid `spdx` file from VCPKG, then I try to use it with `osv-scanner`, but it generates no package sources found. Can you please help me with this issue? [vcpkg.spdx.zip](https://github.com/google/osv-scanner/files/10277401/vcpkg.spdx.zip)

You need to tried once with JSON output . SPDX file may not be supported

**Comment by MFaisalZaki** [comment]
I have tried [spdx-tool](h
[converted.zip](https://github.com/google/osv-scanner/files/10298602/converted.zip)
ttps://github.com/spdx/tools-java/releases/tag/v1.1.3) to convert to JSON. Yet the same issue. I am attaching both the original file and its converted version.

**Comment by Rohan-Kar** [comment]
> I have tried [spdx-tool](https://github.com/spdx/tools-java/releases/tag/v1.1.3) to convert to JSON. Yet the same issue. I am attaching both the original file and its converted version.
> 
> [converted.zip](https://github.com/google/osv-scanner/files/10298602/converted.zip)

you can try with cyclonedx plugin .  https://github.com/CycloneDX/cyclonedx-maven-plugin and generate the bom.json . Hope this will fixed your problem .

**Comment by MFaisalZaki** [comment]
@Rohan-Kar Thanks for the tip. To ensure I use this to generate SBOM from my SPDX file? And if you have any idea how I can use vcpkg with CycloneDX directly, this would be great.

**Comment by MFaisalZaki** [comment]
Update, I have used [cyclonedx-cli](https://github.com/CycloneDX/cyclonedx-cli) to convert from `spdx` to `cdx` using the following command: 
```
cyclonedx-win-x64.exe convert --input-file vcpkg.spdx.json --output-file vcpkg.json --input-format spdxjson --output-format json
```
And I received this output:
```
Scanned CycloneDX SBOM
No package sources found, --help for usage information.
```
The problem still exists. 
[files.zip](https://github.com/google/osv-scanner/files/10298809/files.zip)

**Comment by richncrich** [comment]
I also encountered the same problem. Looking forward to the solution...

**Comment by Rohan-Kar** [comment]
> Update, I have used [cyclonedx-cli](https://github.com/CycloneDX/cyclonedx-cli) to convert from `spdx` to `cdx` using the following command:
> 
> ```
> cyclonedx-win-x64.exe convert --input-file vcpkg.spdx.json --output-file vcpkg.json --input-format spdxjson --output-format json
> ```
> 
> And I received this output:
> 
> ```
> Scanned CycloneDX SBOM
> No package sources found, --help for usage information.
> ```
> 
> The problem still exists. [files.zip](https://github.com/google/osv-scanner/files/10298809/files.zip)

inside your pom.xml file u add the plugin which i have shared in previous reply and save the file . 
`mvn install cyclonedx:makeAggregateBom` then use this command . it will create a target folder inside the target folder u get the bom.json file .  i think this will help you @richncrich

**Comment by MFaisalZaki** [comment]
@Rohan-Kar, I think there is a misunderstanding. I'm creating `SPDX` for C/C++ packages. This file is generated from [vcpkg](https://github.com/microsoft/vcpkg); after debugging with other parties, we found the generated file from `vcpkg` has a missing entry. Moreover, I have chosen the exiv2 package with [OSV entry](https://osv.dev/vulnerability/OSV-2022-830) and regenerated another file with the proper required information. Yet, I receive nothing. As for your instructions, they worked for Java code base applications. 




[vcpkg.spdx.json.zip](https://github.com/google/osv-scanner/files/10327131/vcpkg.spdx.json.zip)

**Comment by oliverchang** [comment]
Hi! 

For CycloneDX and SPDX sboms, scanning currently works if they include Package URLs. 

C/C++ support is limited at this point -- we're addressing this as part of #82.

**Comment by darkdatter** [comment]
Does anyone have an example of what syntax of package URLs osv-scanner is expecting?

**Comment by andrewpollock** [comment]
I thought it was https://github.com/package-url/purl-spec?

**Comment by MDanialSaleem** [comment]
Reproduces on my end.
Steps to reproduce
1. Generate spdx sbom in json format for an NPM project using the sbom generator from [here](https://github.com/opensbom-generator/spdx-sbom-generator/releases/tag/v0.0.15) ```spdx-sbom-generator -f json```
2. Try doing a vulnerability analysis using osv scanner using ```osv-scanner -S bom-npm.json```

Additional information:
1. It does not work even with the spdx format i.e ```osv-scanner -S bom-npm.spdx```.
2. It does work with package-lock files i.e ```osv-scanner -L package-lock.json```

**Comment by another-rex** [comment]
`spdx-sbom-generator` does not work with osv-scanner at the moment because we rely on [package url](https://github.com/package-url/purl-spec) from SBOMs, which `spdx-sbom-generator` does not generate.

Looking at the output of `sbom-spdx-generator`, it has the full package name, but the main element that's missing for osv-scanner is what ecosystem the package belongs to. If we don't have that, osv-scanner cannot scan it. 

We should improve the documentation and osv-scanner's error output for SBOM scanning to clarify this.

**Comment by anotherbridge** [comment]
I can reproduce the same issue with an SBOM generated by [sbom-tool](https://github.com/microsoft/sbom-tool). This uses [package url](https://github.com/package-url/purl-spec) format. An example of the first entry in the packages section of the SBOM generated would be: 

```
{
  "name": "numpy",
  "SPDXID": "SPDXRef-Package-70079897B31469EAC38D1ADC5757D5D6170ADCDF1402938BF4197848D1394F7D",
  "downloadLocation": "NOASSERTION",
  "filesAnalyzed": false,
  "licenseConcluded": "NOASSERTION",
  "licenseInfoFromFiles": [
    "NOASSERTION"
  ],
  "licenseDeclared": "NOASSERTION",
  "copyrightText": "NOASSERTION",
  "versionInfo": "1.24.2",
  "externalRefs": [
    {
      "referenceCategory": "PACKAGE-MANAGER",
      "referenceType": "purl",
      "referenceLocator": "pkg:pypi/numpy@1.24.2"
    }
  ],
  "supplier": "NOASSERTION"
}
```

Trying to scan this SBOM with `osv-scanner --format json --sbom sbom.json` also yields the following result with exit code 128: 

```
{
  "results": null
}
No package sources found, --help for usage information
```

**Comment by oliverchang** [comment]
Thanks @anotherbridge I've filed https://github.com/google/osv-scanner/issues/335 to track a number of SPDX parsing improvements.

In your case specifically, there are a few reasons why we fail to extract packages:

- filename. The SPDX spec says that there should be ".spdx" in the filename: https://spdx.github.io/spdx-spec/v2.3/conformance/#44-standard-data-format-requirements. We currently ignore files that don't match this, but I think we should be more flexible here (tracked in #335). 
- we currently only parse things under "packages" in the SPDX SBOM. We don't look at the root `externalRefs`. This is also tracked in #335.

**Comment by oliverchang** [comment]
Scratch the second part of my last comment. I believe it's just because the filename does not match what we expect. @anotherbridge can you please confirm?

**Comment by anotherbridge** [comment]
@oliverchang Thanks for the information. I can confirm that in my case the reason was the filename. Changing the filename to `*.spdx.json` resolved the issue.
