### ISSUE TITLE
Ability to scan apt, dnf, apk packages, and nix, and take sbom outputs from syft

### ISSUE THREAD

**Issue by edwinjhlee** [google/osv-scanner#991]
I notice this PR a years ago.
https://github.com/google/osv-scanner/pull/128

I am wondering whether the osv-scanner is going to add support to scan the packages in the OS.

**Comment by G-Rath** [comment]
The scanner [already supports](https://google.github.io/osv-scanner/supported-languages-and-lockfiles/#alpine-package-keeper-and-debian-package-keeper) APT and APK scanning, though not [DNF](https://docs.fedoraproject.org/en-US/quick-docs/dnf/).

I have never even heard of that until now, but it looks like its for Fedora so it might be moot until #917 is resolved - still, if someone wants to provide some details on how DNF actually works I don't mind investigating writing a lockfile parser for it.

**Comment by edwinjhlee** [comment]
> The scanner [already supports](https://google.github.io/osv-scanner/supported-languages-and-lockfiles/#alpine-package-keeper-and-debian-package-keeper) APT and APK scanning, though not [DNF](https://docs.fedoraproject.org/en-US/quick-docs/dnf/).
> 
> I have never even heard of that until now, but it looks like its for Fedora so it might be moot until #917 is resolved - still, if someone wants to provide some details on how DNF actually works I don't mind investigating writing a lockfile parser for it.

Thank you. It is very helpful !!!

**Comment by edwinjhlee** [comment]
> The scanner [already supports](https://google.github.io/osv-scanner/supported-languages-and-lockfiles/#alpine-package-keeper-and-debian-package-keeper) APT and APK scanning, though not [DNF](https://docs.fedoraproject.org/en-US/quick-docs/dnf/).
> 
> I have never even heard of that until now, but it looks like its for Fedora so it might be moot until #917 is resolved - still, if someone wants to provide some details on how DNF actually works I don't mind investigating writing a lockfile parser for it.

Since osv cannot currently work well with redhat/fedora, will osv community add support to almal/rocky linux in the future.

I am also curious what need to be done to have brew or macports scanned. The brew and macports build files are open so the vulns can be detected by source versions.

**Comment by edwinjhlee** [comment]
And also, will osv support nix ?

I notice there is a project syft, which can output sbom files.
Is it valuable if osv accept syft output ?

**Comment by another-rex** [comment]
> scan apt

OSV-Scanner can currently scan Debian based apt (https://google.github.io/osv-scanner/supported-languages-and-lockfiles/#alpine-package-keeper-and-debian-package-keeper)

> `dnf`

As stated above, we currently don't support `dnf`, but I created #999 to specifically track the progress of `dnf` support. 

>  apk packages

We also already support alpine apk: (https://google.github.io/osv-scanner/supported-languages-and-lockfiles/#alpine-package-keeper-and-debian-package-keeper)

> nix,

Currently there's no support for nix, and no planned support at the moment. I also don't believe we have advisory information in OSV for nix specifically.

> and take sbom outputs from syft 

This is already supported as well. https://google.github.io/osv-scanner/usage/#specify-sbom
